### ISSUE TITLE
Help with installation needed 

### ISSUE THREAD

**Issue by crnii1** [OK-DMR/ok-dmrlib#1]
Hello,

I am not a tech guy that much so I need some help with installing it. Could you please leave your email address or another contactable form so I can contact you?

Thank you

**Comment by smarek** [comment]
Hey, Github is best place, since the discussions remain public for others, contrary to email, where i have to write the same exact thing in each email.

Can you continue here or in github discussions, or do you need my email.
marek.sebera@gmail.com in that case

**Comment by smarek** [comment]
Just to close this, the question was "can i use ok-dmrlib to parse wav recording from dsd/dsdplus?" answer is "no"
**long answer:**
ok-dmrlib works on bytes/bits, if your data need additional conversion or filtering (eg. filtering from raw on-air channel data to individual bursts in form of bytes), you need to use or develop tools for that. ok-dmrlib does not have the tools to work with binaries/arbitrary air recordings
