### ISSUE TITLE
32 Bit CRC

### ISSUE THREAD

**Issue by alwinhb** [OK-DMR/ok-dmrlib#11]
Hi @smarek 

Can you help me understand the CRC 32 Bit used in this code, 

- For data sample "d6790062620003bf000700000000000000000000" your CRC32 is "210b9a3d"
```
As per my understanding of your code, we are doing the following steps -
1. First is byte swap
o/p: 79d662000062bf03070000000000000000000000
2. Then for each byte, we are doing bit reverse
o/p: 9E6B46000046FDC0E00000000000000000000000
3. And applying crc32 with polynomial: 0X04C11DB7
```
But as I follow the above steps on my code using the same data sample my CRC32 bits come to be different. The other things like CC, and Data/Payload look good while decoding but my CRC Comes out to be different.

**Comment by smarek** [comment]
Well I hope you figured it out, without your code I cannot help, and honestly, you're just re-implementing ok-dmrlib in C/C++ and closed-source, so I'll not support you, unless it's a paid work.
Good luck with your project
