### ISSUE TITLE
[Discuss] Tier3 extension

### ISSUE THREAD

**Issue by mastodon987** [OK-DMR/ok-dmrlib#13]
Hi @smarek. Actually not an issue, just as info. i'm working on tier3 extending your library (currently 361-4 only). now i have almost all types of T3 pdus and elements coded and working cross-checked with dsd-fme. 
But also i have some issue which im not asking for question, just noticing here. Maybe it will save someone time in future.

I wasn't sucessful transmitting CACH, Embedded outbound RC, and MBC bursts over Hytera repeater. With MBC there is one thing interesting. If i send it with correct crc to repeater, then it doesn't transmit. if same but crc16=0, then the same. But when i send to repeater with wrong crc, then it transmit that mbc header over the air. 

I mean MBC is different by Datatype and last_block flag mainly. I guess there is issue in configuration repeater in cps as for handheld radio there are option for CrcMask: PDT/DMR in PS Trunk Developer Configuration. What i'm definitelly sure, that MBC header and continuation packets are constructed well because i get same deinterleaved bitarray as in sample what i downloaded from some dsd-fme thread somewhere in both ways (interleaved<->deinterleaved).

Bad for me is that i dont have any developers.usr file for repeater.
For other mentioned types of pdu maybe i will try them in future to transmit over the repeater.
Still working on it. 
Until finished, i keep it only on my local computer for now.

My goal is to develop full trunk controller for Hytera, ETSI standard only which means no Motorola and Hytera proprietary frames.

**Comment by smarek** [comment]
Hey @mastodon987 glad to hear from you, about CRC, i've seen it as well, at least hytera equipment producing and requiring invalid CRC checksums for some frame types. Good luck, and if you ever publish anything, let me know please.

Neither i have developers.usr file, so i can't help you out there sincerely

Regarding CRC masks and tests, if you have any real-world data, i'd love to include them in the test suite, check out what's already available:
https://github.com/OK-DMR/ok-dmrlib/tree/master/okdmr/tests/dmrlib/etsi/crc

**Comment by mastodon987** [comment]
Unfortunately in my area is just idle T3 CC. So aloha + cach bursts only as real-world data.

**Comment by smarek** [comment]
Well if you have Hytera repeater(s) and few MS (preferably more vendors than just Hytera), you should be able to obtain all of these by working with it and capturing air data? I have RD985 and RD985s at hand, we can do a WWAN setup for tier-III if you're able to capture air..
